services:
  haproxy:
    image: haproxy:2.2
    volumes:
      - test-data:/usr/local/etc/haproxy/haproxy.cfg
  whoami:
    image: traefik/whoami
networks:
  default:
    external: true
    name: test-net
