services:
  haproxy:
    image: haproxy:2.2
    command: cat /usr/local/etc/haproxy/haproxy.cfg
    volumes:
      - ./../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  whoami:
    image: traefik/whoami
networks:
  default:
    external: true
    name: test-net
